export default function PrintFooter() {
  return (
    <div className="hidden print:block mt-8" style={{ fontFamily: "Arial, sans-serif", color: "#000" }}>

      {/* ── Signature Lines ── */}
      <table style={{ width: "100%", borderCollapse: "collapse", marginTop: "32px" }}>
        <tbody>
          <tr>
            <td style={{ width: "33%", textAlign: "center", padding: "0 12px" }}>
              <div style={{ borderTop: "1px solid #000", paddingTop: "6px", fontSize: "11px" }}>
                প্রস্তুতকারক
              </div>
            </td>
            <td style={{ width: "33%", textAlign: "center", padding: "0 12px" }}>
              <div style={{ borderTop: "1px solid #000", paddingTop: "6px", fontSize: "11px" }}>
                যাচাইকারী
              </div>
            </td>
            <td style={{ width: "33%", textAlign: "center", padding: "0 12px" }}>
              <div style={{ borderTop: "1px solid #000", paddingTop: "6px", fontSize: "11px" }}>
                অনুমোদিত স্বাক্ষর
              </div>
            </td>
          </tr>
        </tbody>
      </table>

      {/* ── System Notice ── */}
      <div style={{ marginTop: "20px", borderTop: "1px solid #ccc", paddingTop: "6px", fontSize: "10px", color: "#555", textAlign: "center" }}>
        এটি একটি সিস্টেম জেনারেটেড ডকুমেন্ট। স্বাক্ষর ও সিল বাধ্যতামূলক নয়। &nbsp;|&nbsp; Generated by RentFlow
      </div>
    </div>
  );
}
