name: Deploy Frontend

on:
  push:
    branches: [master]
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 168.144.38.75
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/rentflow
            git fetch origin
            git reset --hard origin/master
            cd frontend
            pnpm install
            pnpm build
            systemctl restart nginx
